Getting and Knowing data

In [1]:
import pandas as pd
import numpy as np

Step 1: Import DB

In [2]:
df = pd.read_csv("chipotle (1).tsv",sep="\t")

In [3]:
df.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [4]:
df.shape

(4622, 5)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [13]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [6]:
df.describe(include="all")

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

loc vs iloc

In [7]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [8]:
df.loc[(df.quantity == 2) & (df.item_name == "Nantucket Nectar"),['order_id','quantity']]

      order_id  quantity
601        247         2
2379       947         2

In [9]:
df.iloc[[9]]

,order_id,quantity,item_name,choice_description,item_price
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [10]:
df.iloc[3:11]

,order_id,quantity,item_name,choice_description,item_price
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45

In [11]:
df.item_price.dtype

dtype('O')

Apply()

In [12]:
df.item_price=df.item_price.apply(lambda x:float( x.replace('$','')))

In [13]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [8]:
df['total_price'] = df['quantity'] * df['item_price']

In [9]:
df.head()

,order_id,quantity,item_name,choice_description,item_price,total_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96

In [10]:
revenue=df.total_price.sum()
print(revenue)

39237.02

Group By:
Which was the most-ordered item?

In [11]:
c = df.groupby("item_name")["quantity"].sum()
c.sort_values(ascending=False).head()

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

In [12]:
df.item_name.value_counts().count()

np.int64(50)

In [63]:
df.item_name.nunique()

50

In [13]:
df.total_price.dtype

dtype('float64')

In [16]:
df.describe(include="all")

,order_id,quantity,item_name,choice_description,item_price,total_price
count,4622.000000,4622.000000,4622,3376,4622.000000,4622.000000
unique,NaN,NaN,50,1043,NaN,NaN
top,NaN,NaN,Chicken Bowl,[Diet Coke],NaN,NaN
freq,NaN,NaN,726,134,NaN,NaN
mean,927.254868,1.075725,NaN,NaN,7.464336,8.489186
std,528.890796,0.410186,NaN,NaN,4.245557,12.632060
min,1.000000,1.000000,NaN,NaN,1.090000,1.090000
25%,477.250000,1.000000,NaN,NaN,3.390000,3.990000
50%,926.000000,1.000000,NaN,NaN,8.750000,8.750000
75%,1393.000000,1.000000,NaN,NaN,9.250000,10.980000
max,1834.000000,15.000000,NaN,NaN,44.250000,663.750000

In [20]:
dates = pd.date_range("20130101", periods=6)

In [23]:
df2=pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

In [27]:
df2.to_numpy()

array([[-0.76766201, -0.5052186 , -0.76540299, -0.6380221 ],
       [-0.75377396,  1.42886196,  0.70141503,  0.71493134],
       [ 0.32614258, -0.94740897,  0.5008372 , -1.59148779],
       [-0.68430546,  0.80833024, -0.72572536, -1.41022705],
       [ 0.04945597,  0.19425019, -0.19712649,  2.05165001],
       [-2.3139167 , -0.57843719,  0.87935908, -0.2241033 ]])

In [28]:
df2

                   A         B         C         D
2013-01-01 -0.767662 -0.505219 -0.765403 -0.638022
2013-01-02 -0.753774  1.428862  0.701415  0.714931
2013-01-03  0.326143 -0.947409  0.500837 -1.591488
2013-01-04 -0.684305  0.808330 -0.725725 -1.410227
2013-01-05  0.049456  0.194250 -0.197126  2.051650
2013-01-06 -2.313917 -0.578437  0.879359 -0.224103

In [30]:
df2.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.767662   -0.753774    0.326143   -0.684305    0.049456   -2.313917
B   -0.505219    1.428862   -0.947409    0.808330    0.194250   -0.578437
C   -0.765403    0.701415    0.500837   -0.725725   -0.197126    0.879359
D   -0.638022    0.714931   -1.591488   -1.410227    2.051650   -0.224103